---
repos:
    -   repo: "https://github.com/pre-commit/pre-commit-hooks"
        rev: "v4.6.0"
        hooks:
            -   id: check-added-large-files
            -   id: check-case-conflict
            -   id: check-merge-conflict
            -   id: check-executables-have-shebangs
            -   id: check-json
            -   id: check-symlinks
            -   id: check-vcs-permalinks
            -   id: check-xml
            -   id: check-yaml
                args: [ --allow-multiple-documents ]
                exclude: "templates/.*"
            -   id: mixed-line-ending

    -   repo: "https://github.com/terraform-docs/terraform-docs"
        rev: "v0.20.0"
        hooks:
            -   always_run: true
                id: "terraform-docs-go"
                entry: "terraform-docs"
                args:
                    - infrastructure

    -   repo: https://github.com/gitleaks/gitleaks
        rev: v8.18.2
        hooks:
            -   id: gitleaks
